apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\asdf\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: rbmq
  name: rbmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rbmq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\asdf\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: rbmq
    spec:
      containers:
        - image: rabbitmq:3-management
          name: rbmq
          resources: {}
      restartPolicy: Always
status: {}
