apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\asdf\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: sqldata
  name: sqldata
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sqldata
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\asdf\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: sqldata
    spec:
      containers:
        - image: mcr.microsoft.com/mssql/server:2019-latest
          name: sqldata
          resources: {}
      restartPolicy: Always
status: {}
