apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: clientapp
  name: clientapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clientapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: clientapp
    spec:
      containers:
        - image: zzaio/clientapp
          name: clientapp
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
