apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: grpcservice
  name: grpcservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grpcservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: grpcservice
    spec:
      containers:
        - image: zzaio/grpcservice
          name: grpcservice
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
