apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: studentapi
  name: studentapi
spec:
  ports:
    - name: "7001"
      port: 7001
      targetPort: 8080
      nodePort: 30001
  type: NodePort
  selector:
    io.kompose.service: studentapi
status:
  loadBalancer: {}
