apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\asdf\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: courseapi
  name: courseapi
spec:
  ports:
    - name: "7002"
      port: 7002
      targetPort: 8080
  selector:
    io.kompose.service: courseapi
status:
  loadBalancer: {}
