apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\asdf\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: rbmq
  name: rbmq
spec:
  ports:
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    io.kompose.service: rbmq
status:
  loadBalancer: {}
